read_hdl -vhdl {driver.vhd}
read_hdl -vhdl {edge_detector.vhd}
read_hdl -vhdl {high_edgedetec.vhd}
read_hdl -vhdl {spc_clockgen.vhd}
read_hdl -vhdl {spi_data_ctrl.vhd}
read_hdl -vhdl {spi_rom.vhd}
read_hdl -vhdl {spi_top_lvl.vhd}
read_hdl -vhdl {driver_SYN.vhd}
read_hdl -vhdl {edgedetector-behaviour.vhd}
read_hdl -vhdl {high_edgedetec-behaviour.vhd}
read_hdl -vhdl {spc_clockgen_SYN.vhd}
read_hdl -vhdl {spi_data_ctrl-behaviour.vhd}
read_hdl -vhdl {spi_rom-behaviour.vhd}
read_hdl -vhdl {spi_data_ctrl_behaviour_cfg.vhd}
read_hdl -vhdl {spi_rom_behaviour_cfg.vhd}
read_hdl -vhdl {high_edgedetec_high_edgedetector_rtl_cfg.vhd}
read_hdl -vhdl {edgedetector_edgedetector_rtl_cfg.vhd}
read_hdl -vhdl {driver_synthesised_cfg.vhd}
read_hdl -vhdl {spc_clockgen_synthesised_cfg.vhd}
read_hdl -vhdl {spi_top_level_structural_cfg.vhd}
